#!/usr/bin/env bash
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
###############################################################################

###############################################################################
# OFBiz initialisation script for use as the entry point in a docker container.
#
# Triggers the loading of data and configuration of various OFBiz properties before
# executing the command given as arguments to the script.
#
# Configuration is applied by rendering a property file or an XML template into
# /ofbiz/config, which precedes ofbiz.jar on the class path, so the rendered values win
# over the ones the image ships. Nothing sensitive is baked into the image: every secret
# is supplied here, at container start, from the environment.
#
#
# Behaviour controlled by environment variables:
#
# OFBIZ_SKIP_INIT
# Any non-empty value will cause this script to skip any initialisation steps.
# Default: <empty>
#
# OFBIZ_PROFILE
# Selects how strictly the deployment secrets are enforced.
# Values:
# - dev:  a missing secret is tolerated. A random per-container admin key is generated so that a clean
#         shutdown still works, and the signing keys are left blank, which leaves the JWT and
#         forgot-password features unusable but lets an unconfigured container boot.
# - prod: a missing secret is a fatal error. OFBIZ_ADMIN_PASSWORD, OFBIZ_ADMIN_KEY,
#         OFBIZ_LOGIN_SECRET_KEY and OFBIZ_JWT_TOKEN_KEY must all be supplied.
# Default: dev
#
# OFBIZ_ADMIN_USER
# The username of the OFBIZ admin user.
# Default: admin
#
# OFBIZ_ADMIN_PASSWORD
# The password of the OFBIZ admin user.
# Default: ofbiz (refused when OFBIZ_PROFILE=prod)
#
# OFBIZ_ADMIN_KEY
# The shared secret the AdminClient presents to shut OFBiz down or ask for its status. Rendered into
# ofbiz.admin.key. Must not contain ':', which AdminServerContainer uses to separate the key from the
# command.
# Default: a random value generated per container (OFBIZ_PROFILE=dev only)
#
# OFBIZ_LOGIN_SECRET_KEY
# The key that encrypts the autogenerated password of the forgot-password feature. Rendered into
# login.secret_key_string. Every instance behind a load balancer must be given the same value.
# Default: <empty> (OFBIZ_PROFILE=dev only, which leaves the feature unusable)
#
# OFBIZ_JWT_TOKEN_KEY
# The key that signs JSON Web Tokens. Rendered into security.token.key. Must be at least 64 characters,
# and every instance behind a load balancer must be given the same value.
# Default: <empty> (OFBIZ_PROFILE=dev only, which leaves the JWT features unusable)
#
# OFBIZ_DATA_LOAD
# Determine what type of data loading is required.
# Default: seed
# Values:
# - none: No data loading is performed.
# - seed: Seed data is loaded.
# - demo: Demo data is loaded.
#
# OFBIZ_HOST
# Specify the hostname used to access OFBiz.
# Used to populate the host-headers-allowed property in framework/security/config/security.properties.
# Default: default value of host-headers-allowed from framework/security/config/security.properties.
#
# OFBIZ_CONTENT_URL_PREFIX
# Used to set the content.url.prefix.secure and content.url.prefix.standard properties in
# framework/webapp/config/url.properties.
# Default: <empty>
#
# OFBIZ_ENABLE_AJP_PORT
# Enable the AJP (Apache JServe Protocol) port to allow communication with OFBiz via a reverse proxy.
# Enabled when this environment variable contains a non-empty value.
# Default value: <empty>
#
# OFBIZ_POSTGRES_HOST
# Sets the name of the PostgreSQL database host.
# If OFBIZ_POSTGRES_HOST is non-empty, the PostgreSQL template is rendered into config/entityengine.xml,
# which points the serving delegators at PostgreSQL; the test delegator stays on embedded H2. If it is
# empty, the whole database configuration step is skipped and the container boots on embedded H2.
# The following OFBIZ_POSTGRES_* environment variables are used to configure access:
# OFBIZ_POSTGRES_PORT               Default: 5432
# OFBIZ_POSTGRES_OFBIZ_DB           Default: ofbiz
# OFBIZ_POSTGRES_OFBIZ_USER         Default: ofbiz
# OFBIZ_POSTGRES_OFBIZ_PASSWORD     Default: ofbiz
# OFBIZ_POSTGRES_OLAP_DB            Default: ofbizolap
# OFBIZ_POSTGRES_OLAP_USER          Default: ofbizolap
# OFBIZ_POSTGRES_OLAP_PASSWORD      Default: ofbizolap
# OFBIZ_POSTGRES_TENANT_DB          Default: ofbiztenant
# OFBIZ_POSTGRES_TENANT_USER        Default: ofbiztenant
# OFBIZ_POSTGRES_TENANT_PASSWORD    Default: ofbiztenant
#
# OFBIZ_DB_POOL_MIN / OFBIZ_DB_POOL_MAX
# Connection pool bounds for each managed PostgreSQL datasource. Both are PER-INSTANCE, so a fleet of n
# instances can open up to n * OFBIZ_DB_POOL_MAX connections per entity group.
# Defaults: 2 and 250
#
# OFBIZ_SCHEMA_INIT
# When set to "true", this container performs a ONE-SHOT schema initialisation and exits without serving
# traffic: the PostgreSQL template is rendered with startup DDL enabled, OFBiz is started once so the
# Entity Engine creates the tables its entity model declares, the template is then re-rendered with
# startup DDL disabled, and the container exits. Requires OFBIZ_POSTGRES_HOST. Every serving start runs
# with startup DDL disabled and therefore needs no DDL privilege.
# Default: false
#
# OFBIZ_DISTRIBUTED_CACHE_CLEAR
# Enables distributed cache clear on the serving delegators, so that more than one instance sharing one
# database invalidates each other's entity caches. Requires the JMS transport named by
# framework/service/config/serviceengine.xml to be configured.
# Default: false
#
# OFBIZ_JVM_ROUTE
# The per-instance sticky-session route id appended to the session cookie. Give every instance a distinct
# value when the load balancer uses sticky sessions. An empty value installs no JVM route.
# Default: jvm1 (as shipped)
#
# OFBIZ_SSL_ACCELERATOR_PORT
# The port on which requests arrive from a TLS-terminating proxy. Every request arriving on it is treated
# as secure, so the port must be reachable only through the proxy. An empty value installs no valve.
# Default: <empty>
#
# OFBIZ_ENABLE_CROSS_SUBDOMAIN_SESSIONS
# Set to "true" to widen the session cookie to the parent domain.
# Default: false
#
# OFBIZ_CONTENT_STORE_PROVIDER
# Where file-backed DataResource content is stored: database (the default, unchanged behaviour),
# filesystem (the runtime/contentstore directory, which may be a shared mount) or s3.
# Default: database
#
# OFBIZ_S3_BUCKET / OFBIZ_S3_REGION / OFBIZ_S3_ENDPOINT
# The bucket and region of the object store, and the endpoint to address instead of the AWS one. Leave
# the endpoint empty for Amazon S3; set an absolute http or https URI for any other S3-compatible store.
# Required when OFBIZ_CONTENT_STORE_PROVIDER=s3: bucket and region.
#
# OFBIZ_S3_ACCESS_KEY_ID / OFBIZ_S3_SECRET_ACCESS_KEY
# Static credentials for the object store. Supply both or neither; with neither, the AWS SDK's default
# credential chain is used, which is how an instance picks up an IAM role.
# Default: <empty>
#
# OFBIZ_S3_PATH_STYLE
# Set to "true" to address the bucket as a path segment rather than as a hostname. Most non-AWS
# S3-compatible stores require it.
# Default: false
#
# OFBIZ_DISABLE_COMPONENTS
# Prevents loading of ofbiz-components.
# Contains a comma separated list of relative paths from the ofbiz sources directory to the ofbiz-component.xml files
# that should be prevented from loading.
# Default: plugins/birt/ofbiz-component.xml
#
# The PostgreSQL JDBC driver is bundled in the image (see dependencies.gradle), so no driver is
# downloaded at start up and OFBIZ_SKIP_DB_DRIVER_DOWNLOAD is obsolete and ignored.
#
# Configuration is applied once and recorded in /ofbiz/runtime/container_state. To re-apply it after
# changing an environment variable - rotating a secret, for instance - delete
# /ofbiz/runtime/container_state/config_applied (and .../db_config_applied for the database) and restart.
#
# Hooks are executed at the various stages of the initialisation process by executing scripts in the following
# directories. Scripts must be executable and have the .sh extension:
#
# /docker-entrypoint-hooks/before-config-applied.d
# Executed before any changes are applied to the OFBiz configuration files.
#
# /docker-entrypoint-hooks/after-config-applied.d
# Executed after any changes are applied to the OFBiz configuration files.
#
# /docker-entrypoint-hooks/before-data-load.d
# Executed before any data loading is about to be performed. Only executed if data loading is required.
# Example usage would be to alter the data to be loaded.
#
# /docker-entrypoint-hooks/additional-data.d
# Any data files (.xml files) in this directory are loaded after seed/demo data.
#
# /docker-entrypoint-hooks/after-data-load.d
# Executed after any data loading has been performed. Only executed if data loading was required.
#
###############################################################################
set -x
set -e

trap shutdown_ofbiz SIGTERM SIGINT

CONTAINER_STATE_DIR="/ofbiz/runtime/container_state"
CONTAINER_DATA_LOADED="$CONTAINER_STATE_DIR/data_loaded"
CONTAINER_ADMIN_LOADED="$CONTAINER_STATE_DIR/admin_loaded"
CONTAINER_CONFIG_APPLIED="$CONTAINER_STATE_DIR/config_applied"
CONTAINER_DB_CONFIG_APPLIED="$CONTAINER_STATE_DIR/db_config_applied"

# The files this script reads from and renders to. The shipped copies under /ofbiz/framework and
# /ofbiz/applications are the sources; the rendered copies under /ofbiz/config are what the JVM reads.
SECURITY_PROPERTIES_SOURCE="framework/security/config/security.properties"
CONTENT_PROPERTIES_SOURCE="applications/content/config/content.properties"
URL_PROPERTIES_SOURCE="framework/webapp/config/url.properties"
START_PROPERTIES_SOURCE="framework/start/src/main/resources/org/apache/ofbiz/base/start/start.properties"
START_PROPERTIES_OVERRIDE="config/org/apache/ofbiz/base/start/start.properties"
CATALINA_COMPONENT="framework/catalina/ofbiz-component.xml"
ENTITY_ENGINE_TEMPLATE="templates/postgres-entityengine.xml"
ENTITY_ENGINE_OVERRIDE="config/entityengine.xml"

###############################################################################
# Report a configuration fault and stop the container.
# A fault is fatal rather than a warning: a container that carries on with a setting it could not apply
# would serve traffic in a configuration the operator did not ask for.
# $1 - the message
config_fatal() {
  echo "ERROR: $1" >&2
  exit 1
}

###############################################################################
# Refuse a value that cannot be substituted into a sed program or an XML attribute.
# Only the characters that would break the substitution itself are refused, so a password may contain
# anything else. Called with tracing already disabled for anything secret.
# $1 - variable name, for the message. $2 - the value.
require_substitutable() {
  if [ -n "$2" ] && printf '%s' "$2" | LC_ALL=C grep -q '[|&\\<>"'"'"']\|[[:cntrl:]]'; then
    config_fatal "$1 must not contain a control character or any of: | & \\ < > \" '"
  fi
}

###############################################################################
# Refuse a value that is not one of an accepted set.
# $1 - variable name, $2 - the value, $3.. - the accepted values
require_enum() {
  local name="$1" value="$2"
  shift 2
  local accepted
  for accepted; do
    if [ "$value" = "$accepted" ]; then
      return 0
    fi
  done
  config_fatal "$name=$value is not one of: $*"
}

###############################################################################
# Refuse a value that is not a positive integer.
# $1 - variable name, $2 - the value
require_positive_integer() {
  case "$2" in
  '' | *[!0-9]*) config_fatal "$1=$2 must be a positive integer" ;;
  0*[!0] | 0) config_fatal "$1=$2 must be a positive integer" ;;
  esac
}

###############################################################################
# Validate and apply defaults to any environment variables used by this script.
# See script header for environment variable descriptions.
ofbiz_setup_env() {
  OFBIZ_PROFILE=${OFBIZ_PROFILE:-dev}
  require_enum OFBIZ_PROFILE "$OFBIZ_PROFILE" dev prod

  case "$OFBIZ_DATA_LOAD" in
  none | seed | demo) ;;
  *)
    OFBIZ_DATA_LOAD="seed"
    ;;
  esac

  OFBIZ_ADMIN_USER=${OFBIZ_ADMIN_USER:-admin}

  OFBIZ_POSTGRES_PORT=${OFBIZ_POSTGRES_PORT:-5432}
  require_positive_integer OFBIZ_POSTGRES_PORT "$OFBIZ_POSTGRES_PORT"

  # Tracing off while the database credentials are defaulted, so that a supplied password is not echoed
  # into the container log by "set -x" and from there into "docker logs" and any log collector (CWE-532).
  { set +x; } 2>/dev/null
  OFBIZ_POSTGRES_OFBIZ_DB=${OFBIZ_POSTGRES_OFBIZ_DB:-ofbiz}
  OFBIZ_POSTGRES_OFBIZ_USER=${OFBIZ_POSTGRES_OFBIZ_USER:-ofbiz}
  OFBIZ_POSTGRES_OFBIZ_PASSWORD=${OFBIZ_POSTGRES_OFBIZ_PASSWORD:-ofbiz}

  OFBIZ_POSTGRES_OLAP_DB=${OFBIZ_POSTGRES_OLAP_DB:-ofbizolap}
  OFBIZ_POSTGRES_OLAP_USER=${OFBIZ_POSTGRES_OLAP_USER:-ofbizolap}
  OFBIZ_POSTGRES_OLAP_PASSWORD=${OFBIZ_POSTGRES_OLAP_PASSWORD:-ofbizolap}

  OFBIZ_POSTGRES_TENANT_DB=${OFBIZ_POSTGRES_TENANT_DB:-ofbiztenant}
  OFBIZ_POSTGRES_TENANT_USER=${OFBIZ_POSTGRES_TENANT_USER:-ofbiztenant}
  OFBIZ_POSTGRES_TENANT_PASSWORD=${OFBIZ_POSTGRES_TENANT_PASSWORD:-ofbiztenant}
  set -x

  OFBIZ_DB_POOL_MIN=${OFBIZ_DB_POOL_MIN:-2}
  OFBIZ_DB_POOL_MAX=${OFBIZ_DB_POOL_MAX:-250}
  require_positive_integer OFBIZ_DB_POOL_MIN "$OFBIZ_DB_POOL_MIN"
  require_positive_integer OFBIZ_DB_POOL_MAX "$OFBIZ_DB_POOL_MAX"
  if [ "$OFBIZ_DB_POOL_MIN" -gt "$OFBIZ_DB_POOL_MAX" ]; then
    config_fatal "OFBIZ_DB_POOL_MIN=$OFBIZ_DB_POOL_MIN is greater than OFBIZ_DB_POOL_MAX=$OFBIZ_DB_POOL_MAX"
  fi

  OFBIZ_SCHEMA_INIT=${OFBIZ_SCHEMA_INIT:-false}
  require_enum OFBIZ_SCHEMA_INIT "$OFBIZ_SCHEMA_INIT" true false
  if [ "$OFBIZ_SCHEMA_INIT" = "true" ] && [ -z "$OFBIZ_POSTGRES_HOST" ]; then
    config_fatal "OFBIZ_SCHEMA_INIT=true requires OFBIZ_POSTGRES_HOST. The embedded H2 database creates its own schema on every start, so it needs no initialisation run."
  fi

  OFBIZ_DISTRIBUTED_CACHE_CLEAR=${OFBIZ_DISTRIBUTED_CACHE_CLEAR:-false}
  require_enum OFBIZ_DISTRIBUTED_CACHE_CLEAR "$OFBIZ_DISTRIBUTED_CACHE_CLEAR" true false

  OFBIZ_JVM_ROUTE=${OFBIZ_JVM_ROUTE-jvm1}
  require_substitutable OFBIZ_JVM_ROUTE "$OFBIZ_JVM_ROUTE"

  OFBIZ_SSL_ACCELERATOR_PORT=${OFBIZ_SSL_ACCELERATOR_PORT:-}
  if [ -n "$OFBIZ_SSL_ACCELERATOR_PORT" ]; then
    require_positive_integer OFBIZ_SSL_ACCELERATOR_PORT "$OFBIZ_SSL_ACCELERATOR_PORT"
  fi

  OFBIZ_ENABLE_CROSS_SUBDOMAIN_SESSIONS=${OFBIZ_ENABLE_CROSS_SUBDOMAIN_SESSIONS:-false}
  require_enum OFBIZ_ENABLE_CROSS_SUBDOMAIN_SESSIONS "$OFBIZ_ENABLE_CROSS_SUBDOMAIN_SESSIONS" true false

  OFBIZ_CONTENT_STORE_PROVIDER=${OFBIZ_CONTENT_STORE_PROVIDER:-database}
  require_enum OFBIZ_CONTENT_STORE_PROVIDER "$OFBIZ_CONTENT_STORE_PROVIDER" database filesystem s3

  OFBIZ_S3_BUCKET=${OFBIZ_S3_BUCKET:-}
  OFBIZ_S3_REGION=${OFBIZ_S3_REGION:-}
  OFBIZ_S3_ENDPOINT=${OFBIZ_S3_ENDPOINT:-}
  OFBIZ_S3_PATH_STYLE=${OFBIZ_S3_PATH_STYLE:-false}
  require_enum OFBIZ_S3_PATH_STYLE "$OFBIZ_S3_PATH_STYLE" true false
  require_substitutable OFBIZ_S3_BUCKET "$OFBIZ_S3_BUCKET"
  require_substitutable OFBIZ_S3_REGION "$OFBIZ_S3_REGION"
  require_substitutable OFBIZ_S3_ENDPOINT "$OFBIZ_S3_ENDPOINT"
  if [ "$OFBIZ_CONTENT_STORE_PROVIDER" = "s3" ]; then
    if [ -z "$OFBIZ_S3_BUCKET" ] || [ -z "$OFBIZ_S3_REGION" ]; then
      config_fatal "OFBIZ_CONTENT_STORE_PROVIDER=s3 requires OFBIZ_S3_BUCKET and OFBIZ_S3_REGION."
    fi
  fi

  OFBIZ_DISABLE_COMPONENTS=${OFBIZ_DISABLE_COMPONENTS-plugins/birt/ofbiz-component.xml}

  resolve_deployment_secrets
}

###############################################################################
# Resolve the four deployment secrets, failing fast in the prod profile.
#
# Tracing is disabled for the whole function - and re-enabled on the way out - so that no secret is
# echoed into the container log, which "docker logs" and any log collector would then hold (CWE-532).
resolve_deployment_secrets() {
  { set +x; } 2>/dev/null

  if [ "$OFBIZ_PROFILE" = "prod" ]; then
    local missing=""
    [ -n "${OFBIZ_ADMIN_PASSWORD:-}" ] || missing="$missing OFBIZ_ADMIN_PASSWORD"
    [ -n "${OFBIZ_ADMIN_KEY:-}" ] || missing="$missing OFBIZ_ADMIN_KEY"
    [ -n "${OFBIZ_LOGIN_SECRET_KEY:-}" ] || missing="$missing OFBIZ_LOGIN_SECRET_KEY"
    [ -n "${OFBIZ_JWT_TOKEN_KEY:-}" ] || missing="$missing OFBIZ_JWT_TOKEN_KEY"
    if [ -n "$missing" ]; then
      config_fatal "OFBIZ_PROFILE=prod requires every deployment secret to be supplied. Missing:$missing. See DOCKER.adoc."
    fi
  fi

  OFBIZ_ADMIN_PASSWORD=${OFBIZ_ADMIN_PASSWORD:-ofbiz}

  # Generated rather than left empty in the dev profile: with no key at all the AdminClient cannot
  # authenticate, so "ofbiz --shutdown" and the SIGTERM handler below could not stop the container. The
  # value lives for the life of the container and is never written to the log.
  if [ -z "${OFBIZ_ADMIN_KEY:-}" ]; then
    OFBIZ_ADMIN_KEY=$(tr --delete --complement A-Za-z0-9 </dev/urandom | head --bytes=32)
    echo "OFBIZ_ADMIN_KEY was not supplied, so a random per-container admin key was generated."
  fi
  case "$OFBIZ_ADMIN_KEY" in
  *:*)
    config_fatal "OFBIZ_ADMIN_KEY must not contain ':'. AdminServerContainer reads a request as key:command and compares everything before the first ':' with the key, so a key containing one can never match."
    ;;
  esac
  require_substitutable OFBIZ_ADMIN_KEY "$OFBIZ_ADMIN_KEY"

  OFBIZ_LOGIN_SECRET_KEY=${OFBIZ_LOGIN_SECRET_KEY:-}
  OFBIZ_JWT_TOKEN_KEY=${OFBIZ_JWT_TOKEN_KEY:-}
  require_substitutable OFBIZ_LOGIN_SECRET_KEY "$OFBIZ_LOGIN_SECRET_KEY"
  require_substitutable OFBIZ_JWT_TOKEN_KEY "$OFBIZ_JWT_TOKEN_KEY"
  if [ -n "$OFBIZ_JWT_TOKEN_KEY" ] && [ ${#OFBIZ_JWT_TOKEN_KEY} -lt 64 ]; then
    config_fatal "OFBIZ_JWT_TOKEN_KEY must be at least 64 characters: JWTManager rejects a shorter key."
  fi

  OFBIZ_S3_ACCESS_KEY_ID=${OFBIZ_S3_ACCESS_KEY_ID:-}
  OFBIZ_S3_SECRET_ACCESS_KEY=${OFBIZ_S3_SECRET_ACCESS_KEY:-}
  require_substitutable OFBIZ_S3_ACCESS_KEY_ID "$OFBIZ_S3_ACCESS_KEY_ID"
  require_substitutable OFBIZ_S3_SECRET_ACCESS_KEY "$OFBIZ_S3_SECRET_ACCESS_KEY"
  if { [ -n "$OFBIZ_S3_ACCESS_KEY_ID" ] && [ -z "$OFBIZ_S3_SECRET_ACCESS_KEY" ]; } \
    || { [ -z "$OFBIZ_S3_ACCESS_KEY_ID" ] && [ -n "$OFBIZ_S3_SECRET_ACCESS_KEY" ]; }; then
    config_fatal "OFBIZ_S3_ACCESS_KEY_ID and OFBIZ_S3_SECRET_ACCESS_KEY are supplied together, or neither is supplied and the AWS SDK's default credential chain is used."
  fi

  set -x
}

###############################################################################
# Create the runtime container state directory used to track which initialisation
# steps have been run for the container.
# This directory should be hosted on a volume that persists for the life of the container.
create_ofbiz_runtime_directories() {
  if [ ! -d "$CONTAINER_STATE_DIR" ]; then
    mkdir --parents "$CONTAINER_STATE_DIR"
  fi
}

###############################################################################
# Execute the shell scripts at the paths passed to this function.
# Args:
# 1:  Name of the hook stage being executed. Used for logging.
# 2+: Variable number of paths to the shell scripts to be executed.
#     Only scripts with the .sh extension are executed.
#     Scripts will be sourced if they are not executable.
run_init_hooks() {
  local hookStage="$1"
  shift
  local filePath
  for filePath; do
    case "$filePath" in
    *.sh)
      if [ -x "$filePath" ]; then
        printf '%s: running %s\n' "$hookStage" "$filePath"
        "$filePath"
      else
        printf '%s: sourcing %s\n' "$hookStage" "$filePath"
        . "$filePath"
      fi
      ;;
    *)
      printf '%s: Not a script. Ignoring %s\n' "$hookStage" "$filePath"
      ;;
    esac
  done
}

###############################################################################
# If required, load data into OFBiz.
load_data() {
  if [ ! -f "$CONTAINER_DATA_LOADED" ]; then
    run_init_hooks before-data-load /docker-entrypoint-hooks/before-data-load.d/*

    case "$OFBIZ_DATA_LOAD" in
    none) ;;

    seed)
      /ofbiz/bin/ofbiz --load-data readers=seed,seed-initial
      ;;

    demo)
      /ofbiz/bin/ofbiz --load-data
      # Demo data includes the admin user so indicate that the user is already loaded.
      touch "$CONTAINER_ADMIN_LOADED"
      ;;
    esac

    # Load any additional data files provided.
    if [ -z "$(find /docker-entrypoint-hooks/additional-data.d/ -prune -empty)" ]; then
      /ofbiz/bin/ofbiz --load-data dir=/docker-entrypoint-hooks/additional-data.d
    fi

    touch "$CONTAINER_DATA_LOADED"

    run_init_hooks after-data-load /docker-entrypoint-hooks/after-data-load.d/*
  fi
}

###############################################################################
# Create and load the password hash for the admin user.
load_admin_user() {
  if [ ! -f "$CONTAINER_ADMIN_LOADED" ]; then
    { set +x; } 2>/dev/null
    TMPFILE=$(mktemp)

    # Concatenate a random salt and the admin password.
    SALT=$(tr --delete --complement A-Za-z0-9 </dev/urandom | head --bytes=16)
    SALT_AND_PASSWORD="${SALT}${OFBIZ_ADMIN_PASSWORD}"

    # Take a SHA-1 hash of the combined salt and password and strip off any additional output form the sha1sum utility.
    SHA1SUM_ASCII_HEX=$(printf "$SALT_AND_PASSWORD" | sha1sum | cut --delimiter=' ' --fields=1 --zero-terminated | tr --delete '\000')

    # Convert the ASCII Hex representation of the hash to raw bytes by inserting escape sequences and running
    # through the printf command. Encode the result as URL base 64 and remove padding.
    SHA1SUM_ESCAPED_STRING=$(printf "$SHA1SUM_ASCII_HEX" | sed -e 's/\(..\)\.\?/\\x\1/g')
    SHA1SUM_BASE64=$(printf "$SHA1SUM_ESCAPED_STRING" | basenc --base64url --wrap=0 | tr --delete '=')

    # Concatenate the hash type, salt and hash as the encoded password value.
    ENCODED_PASSWORD_HASH="\$SHA\$${SALT}\$${SHA1SUM_BASE64}"

    # Populate the login data template
    sed "s/@userLoginId@/$OFBIZ_ADMIN_USER/g; s/currentPassword=\".*\"/currentPassword=\"$ENCODED_PASSWORD_HASH\"/g;" framework/resources/templates/AdminUserLoginData.xml >"$TMPFILE"
    set -x

    # Load data from the populated template.
    /ofbiz/bin/ofbiz --load-data "file=$TMPFILE"

    rm "$TMPFILE"

    touch "$CONTAINER_ADMIN_LOADED"
  fi
}

###############################################################################
# Modify the given ofbiz-component configuration XML file to set the root
# component's 'enabled' attribute to false.
# $1 - Path to the XML file to be modified.
disable_component() {
  XML_FILE="/ofbiz/$1"
  if [ -f "$XML_FILE" ]; then
    TMPFILE=$(mktemp)
    xsltproc /ofbiz/disable-component.xslt "$XML_FILE" > "$TMPFILE"
    mv "$TMPFILE" "$XML_FILE"
  else
    echo "Cannot find ofbiz-component configuration file. Not disabling component: $XML_FILE"
  fi
}

###############################################################################
# Modify the given ofbiz-component configuration XML files to set their root
# components' 'enabled' attribute to false.
# $1 - Comma separated list of paths to configuration XML files to be modified.
disable_components() {
  COMMA_SEPARATED_PATHS=$1

  # Remove spaces after commas
  COMMA_SEPARATED_PATHS="${COMMA_SEPARATED_PATHS//, /,}"

  [ -z "$COMMA_SEPARATED_PATHS" ] && return 0

  # Split on commas into $1 $2 ...
  oldIFS=$IFS
  IFS=,
  set -- $COMMA_SEPARATED_PATHS    # <- no quotes, use -- to avoid option parsing
  IFS=$oldIFS

  # Iterate through the split arguments
  while [ -n "$1" ]; do
    disable_component "$1"
    shift
  done
}

###############################################################################
# Render the two deployment signing keys into config/security.properties, together with the allowed host
# headers. One rendering rather than two, because both write the same file and the second would otherwise
# discard the first.
#
# Tracing is disabled for the whole function so that no key reaches the container log.
apply_security_properties() {
  { set +x; } 2>/dev/null
  local expressions=()

  if [ -n "$OFBIZ_HOST" ]; then
    expressions+=(--expression="s|^host-headers-allowed=.*|host-headers-allowed=${OFBIZ_HOST}|")
  fi
  if [ -n "$OFBIZ_LOGIN_SECRET_KEY" ]; then
    expressions+=(--expression="s|^login.secret_key_string=.*|login.secret_key_string=${OFBIZ_LOGIN_SECRET_KEY}|")
  fi
  if [ -n "$OFBIZ_JWT_TOKEN_KEY" ]; then
    expressions+=(--expression="s|^security.token.key=.*|security.token.key=${OFBIZ_JWT_TOKEN_KEY}|")
  fi

  if [ ${#expressions[@]} -eq 0 ]; then
    set -x
    return 0
  fi

  sed "${expressions[@]}" "$SECURITY_PROPERTIES_SOURCE" >config/security.properties
  # Readable by the ofbiz user alone: the rendered file holds live signing keys and the /ofbiz/config
  # volume may be shared with other containers or inspected on the host.
  chmod 600 config/security.properties
  set -x
  echo "Rendered config/security.properties"
}

###############################################################################
# Render the admin key into both files that need it: the class path override the JVM reads, and the
# shipped copy that docker/send_ofbiz_stop_signal.sh reads when the container is asked to stop. One sed
# program, two destinations - the key would otherwise be readable by the JVM but not by the helper that
# has to authenticate a shutdown request.
#
# Tracing is disabled for the whole function so that the key does not reach the container log.
apply_admin_key() {
  { set +x; } 2>/dev/null
  local program="s|^#\{0,1\}ofbiz.admin.key=.*|ofbiz.admin.key=${OFBIZ_ADMIN_KEY}|"

  mkdir --parents "$(dirname "$START_PROPERTIES_OVERRIDE")"
  sed "$program" "$START_PROPERTIES_SOURCE" >"$START_PROPERTIES_OVERRIDE"
  chmod 600 "$START_PROPERTIES_OVERRIDE"

  sed --in-place "$program" "$START_PROPERTIES_SOURCE"
  chmod 600 "$START_PROPERTIES_SOURCE"
  set -x
  echo "Rendered the admin key into $START_PROPERTIES_OVERRIDE and $START_PROPERTIES_SOURCE"
}

###############################################################################
# Render the content storage configuration into config/content.properties.
#
# Tracing is disabled for the whole function so that the object store's secret access key does not reach
# the container log.
apply_content_store() {
  if [ "$OFBIZ_CONTENT_STORE_PROVIDER" = "database" ] && [ -z "$OFBIZ_S3_BUCKET" ] && [ -z "$OFBIZ_S3_REGION" ] \
    && [ -z "$OFBIZ_S3_ENDPOINT" ] && [ -z "$OFBIZ_S3_ACCESS_KEY_ID" ] && [ -z "$OFBIZ_S3_SECRET_ACCESS_KEY" ] \
    && [ "$OFBIZ_S3_PATH_STYLE" = "false" ]; then
    # Nothing to change: the shipped content.properties already says exactly this. Not rendering it leaves
    # an operator-mounted config/content.properties alone.
    return 0
  fi
  { set +x; } 2>/dev/null
  sed \
    --expression="s|^content.store.provider=.*|content.store.provider=${OFBIZ_CONTENT_STORE_PROVIDER}|" \
    --expression="s|^content.store.s3.bucket=.*|content.store.s3.bucket=${OFBIZ_S3_BUCKET}|" \
    --expression="s|^content.store.s3.region=.*|content.store.s3.region=${OFBIZ_S3_REGION}|" \
    --expression="s|^content.store.s3.endpoint=.*|content.store.s3.endpoint=${OFBIZ_S3_ENDPOINT}|" \
    --expression="s|^content.store.s3.access.key.id=.*|content.store.s3.access.key.id=${OFBIZ_S3_ACCESS_KEY_ID}|" \
    --expression="s|^content.store.s3.secret.access.key=.*|content.store.s3.secret.access.key=${OFBIZ_S3_SECRET_ACCESS_KEY}|" \
    --expression="s|^content.store.s3.path.style=.*|content.store.s3.path.style=${OFBIZ_S3_PATH_STYLE}|" \
    "$CONTENT_PROPERTIES_SOURCE" >config/content.properties
  chmod 600 config/content.properties
  set -x
  echo "Rendered config/content.properties with the [$OFBIZ_CONTENT_STORE_PROVIDER] content store provider"
}

###############################################################################
# Apply the load-balancer settings to the Tomcat container descriptor.
#
# Patched in place rather than rendered into config/, because ofbiz-component.xml is a component
# descriptor read from its component directory rather than a property resource resolved on the class path.
# This is the same mechanism the AJP change below has always used.
apply_load_balancer_settings() {
  sed --in-place \
    --expression="s|<property name=\"jvm-route\" value=\"[^\"]*\"/>|<property name=\"jvm-route\" value=\"${OFBIZ_JVM_ROUTE}\"/>|" \
    --expression="s|<property name=\"ssl-accelerator-port\" value=\"[^\"]*\"/>|<property name=\"ssl-accelerator-port\" value=\"${OFBIZ_SSL_ACCELERATOR_PORT}\"/>|" \
    --expression="s|<property name=\"enable-cross-subdomain-sessions\" value=\"[^\"]*\"/>|<property name=\"enable-cross-subdomain-sessions\" value=\"${OFBIZ_ENABLE_CROSS_SUBDOMAIN_SESSIONS}\"/>|" \
    "$CATALINA_COMPONENT"

  if [ -n "$OFBIZ_SSL_ACCELERATOR_PORT" ]; then
    echo "WARNING: every request arriving on port $OFBIZ_SSL_ACCELERATOR_PORT will be treated as secure. That port must be reachable only through the TLS-terminating proxy; restrict it in the network layer. See DOCKER.adoc."
  fi
}

###############################################################################
# Apply any configuration changes required.
# Changed property files need to be placed in /ofbiz/config so they appear earlier
# in the classpath and override the build-time copies of the properties in ofbiz.jar.
apply_configuration() {
  if [ ! -f "$CONTAINER_CONFIG_APPLIED" ]; then
    run_init_hooks before-config-applied /docker-entrypoint-hooks/before-config-applied.d/*

    if [ -n "$OFBIZ_ENABLE_AJP_PORT" ]; then
      # Configure tomcat to listen for AJP connections on all interfaces within the container.
      sed --in-place \
        '/<property name="ajp-connector" value="connector">/ a <property name="address" value="0.0.0.0"/>' \
        "$CATALINA_COMPONENT"
    fi

    apply_security_properties
    apply_admin_key
    apply_content_store
    apply_load_balancer_settings

    if [ -n "$OFBIZ_CONTENT_URL_PREFIX" ]; then
      sed \
        --expression="s#content.url.prefix.secure=.*#content.url.prefix.secure=${OFBIZ_CONTENT_URL_PREFIX}#;" \
        --expression="s#content.url.prefix.standard=.*#content.url.prefix.standard=${OFBIZ_CONTENT_URL_PREFIX}#;" \
        "$URL_PROPERTIES_SOURCE" >config/url.properties
    fi

    if [ -n "$OFBIZ_DISABLE_COMPONENTS" ]; then
      disable_components "$OFBIZ_DISABLE_COMPONENTS"
    fi

    touch "$CONTAINER_CONFIG_APPLIED"
    run_init_hooks after-config-applied /docker-entrypoint-hooks/after-config-applied.d/*
  fi
}

###############################################################################
# Render the PostgreSQL entity engine configuration.
# $1 - the check-on-start value, $2 - the add-missing-on-start value.
#
# Tracing is disabled for the whole function so that the three database passwords do not reach the
# container log.
render_entity_engine() {
  { set +x; } 2>/dev/null
  local checkOnStart="$1" addMissingOnStart="$2"

  require_substitutable OFBIZ_POSTGRES_HOST "$OFBIZ_POSTGRES_HOST"
  local name
  for name in OFBIZ_POSTGRES_OFBIZ_DB OFBIZ_POSTGRES_OFBIZ_USER OFBIZ_POSTGRES_OFBIZ_PASSWORD \
    OFBIZ_POSTGRES_OLAP_DB OFBIZ_POSTGRES_OLAP_USER OFBIZ_POSTGRES_OLAP_PASSWORD \
    OFBIZ_POSTGRES_TENANT_DB OFBIZ_POSTGRES_TENANT_USER OFBIZ_POSTGRES_TENANT_PASSWORD; do
    require_substitutable "$name" "${!name}"
  done

  sed \
    --expression="s|@HOST@|$OFBIZ_POSTGRES_HOST|g" \
    --expression="s|@PORT@|$OFBIZ_POSTGRES_PORT|g" \
    --expression="s|@OFBIZ_DB@|$OFBIZ_POSTGRES_OFBIZ_DB|g" \
    --expression="s|@OFBIZ_USERNAME@|$OFBIZ_POSTGRES_OFBIZ_USER|g" \
    --expression="s|@OFBIZ_PASSWORD@|$OFBIZ_POSTGRES_OFBIZ_PASSWORD|g" \
    --expression="s|@OLAP_DB@|$OFBIZ_POSTGRES_OLAP_DB|g" \
    --expression="s|@OLAP_USERNAME@|$OFBIZ_POSTGRES_OLAP_USER|g" \
    --expression="s|@OLAP_PASSWORD@|$OFBIZ_POSTGRES_OLAP_PASSWORD|g" \
    --expression="s|@TENANT_DB@|$OFBIZ_POSTGRES_TENANT_DB|g" \
    --expression="s|@TENANT_USERNAME@|$OFBIZ_POSTGRES_TENANT_USER|g" \
    --expression="s|@TENANT_PASSWORD@|$OFBIZ_POSTGRES_TENANT_PASSWORD|g" \
    --expression="s|@CHECK_ON_START@|$checkOnStart|g" \
    --expression="s|@ADD_MISSING_ON_START@|$addMissingOnStart|g" \
    --expression="s|@DISTRIBUTED_CACHE_CLEAR@|$OFBIZ_DISTRIBUTED_CACHE_CLEAR|g" \
    --expression="s|@DB_POOL_MIN@|$OFBIZ_DB_POOL_MIN|g" \
    --expression="s|@DB_POOL_MAX@|$OFBIZ_DB_POOL_MAX|g" \
    "$ENTITY_ENGINE_TEMPLATE" >"$ENTITY_ENGINE_OVERRIDE"
  chmod 600 "$ENTITY_ENGINE_OVERRIDE"
  set -x

  # A token that survived would be used verbatim as a host name, a password or a boolean, so the start is
  # refused instead. The check names no value, only the token that is still there.
  local survivors
  survivors=$(grep --only-matching '@[A-Z_]\{2,\}@' "$ENTITY_ENGINE_OVERRIDE" | sort --unique | tr '\n' ' ') || survivors=""
  if [ -n "$survivors" ]; then
    config_fatal "Rendered $ENTITY_ENGINE_OVERRIDE still contains unsubstituted tokens: $survivors. The template and this script have diverged."
  fi
  echo "Rendered $ENTITY_ENGINE_OVERRIDE with startup DDL check-on-start=$checkOnStart add-missing-on-start=$addMissingOnStart"
}

###############################################################################
# Set up the connection to the OFBiz database.
# Nothing is rendered when OFBIZ_POSTGRES_HOST is empty, so an unconfigured container boots on the
# embedded H2 database exactly as it always has.
configure_database() {
  if [ ! -f "$CONTAINER_DB_CONFIG_APPLIED" ]; then
    if [ -n "$OFBIZ_POSTGRES_HOST" ]; then
      render_entity_engine false false
    fi

    touch "$CONTAINER_DB_CONFIG_APPLIED"
  fi
}

###############################################################################
# Perform the one-shot schema initialisation and exit, when it was asked for.
#
# The schema is created by the Entity Engine itself from the entity model - no migration framework, no
# hand-written DDL - by starting OFBiz once with startup DDL enabled and loading nothing. The
# configuration is then rewritten with startup DDL disabled, so that this container's own /ofbiz/config
# volume cannot be reused by a serving instance with DDL still enabled.
run_schema_init() {
  if [ "$OFBIZ_SCHEMA_INIT" != "true" ]; then
    return 0
  fi

  echo "OFBIZ_SCHEMA_INIT=true: creating the database schema from the entity model, then exiting."
  render_entity_engine true true
  /ofbiz/bin/ofbiz --load-data readers=none
  render_entity_engine false false
  echo "Schema initialisation is complete. Start the serving instances now; they issue no DDL and need no DDL privilege."
  exit 0
}

###############################################################################
# Send a shutdown signal to OFBiz
shutdown_ofbiz() {
  /ofbiz/send_ofbiz_stop_signal.sh
}

_main() {
  if [ -z "$OFBIZ_SKIP_INIT" ]; then
    ofbiz_setup_env
    create_ofbiz_runtime_directories
    configure_database
    apply_configuration
    run_schema_init
    load_data
    load_admin_user
  fi

  unset OFBIZ_SKIP_INIT
  unset OFBIZ_PROFILE
  unset OFBIZ_ADMIN_USER
  unset OFBIZ_ADMIN_PASSWORD
  unset OFBIZ_ADMIN_KEY
  unset OFBIZ_LOGIN_SECRET_KEY
  unset OFBIZ_JWT_TOKEN_KEY
  unset OFBIZ_DATA_LOAD
  unset OFBIZ_ENABLE_AJP_PORT
  unset OFBIZ_HOST
  unset OFBIZ_CONTENT_URL_PREFIX
  unset OFBIZ_POSTGRES_PORT
  unset OFBIZ_POSTGRES_OFBIZ_DB
  unset OFBIZ_POSTGRES_OFBIZ_USER
  unset OFBIZ_POSTGRES_OFBIZ_PASSWORD
  unset OFBIZ_POSTGRES_OLAP_DB
  unset OFBIZ_POSTGRES_OLAP_USER
  unset OFBIZ_POSTGRES_OLAP_PASSWORD
  unset OFBIZ_POSTGRES_TENANT_DB
  unset OFBIZ_POSTGRES_TENANT_USER
  unset OFBIZ_POSTGRES_TENANT_PASSWORD
  unset OFBIZ_DB_POOL_MIN
  unset OFBIZ_DB_POOL_MAX
  unset OFBIZ_SCHEMA_INIT
  unset OFBIZ_DISTRIBUTED_CACHE_CLEAR
  unset OFBIZ_JVM_ROUTE
  unset OFBIZ_SSL_ACCELERATOR_PORT
  unset OFBIZ_ENABLE_CROSS_SUBDOMAIN_SESSIONS
  unset OFBIZ_CONTENT_STORE_PROVIDER
  unset OFBIZ_S3_BUCKET
  unset OFBIZ_S3_REGION
  unset OFBIZ_S3_ENDPOINT
  unset OFBIZ_S3_ACCESS_KEY_ID
  unset OFBIZ_S3_SECRET_ACCESS_KEY
  unset OFBIZ_S3_PATH_STYLE

  # Continue loading OFBiz.
  exec "$@"
}

_main "$@"
